version: 2
updates:
  # Configuração para dependências do Maven (pom.xml)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    # Garante que as atualizações respeitem o Java 17
    target-branch: "main" 
    open-pull-requests-limit: 5
    
    # Opcional: Agrupar atualizações para não poluir o PR
    groups:
      quarkus-dependencies:
        patterns:
          - "io.quarkus*"
          - "org.jboss.resteasy*"

  # Configuração para GitHub Actions (sempre bom manter atualizado)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
